### ISSUE TITLE
Problème de création de compte 

### ISSUE THREAD

**Issue by Bdamien26** [Noumaa/MatchJob#6]
Bonjour,
Voila à la fin du processus de création de compte il y a une erreur "Such route does not exist". Pourriez-vous regarder ? 
Cordialement 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/94056110/235688820-f23408bb-20e3-4523-8150-aebdbeeb17ab.png)

**Comment by AFelix20100** [comment]
Bonjour ! 

Je viens de voir le problème, je vais le corriger. Merci de l'avoir signalé !

Cordialement

ARTHUR Félix
